language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
  - TASK=test:gas:ci
matrix:
  fast_finish: true
  allow_failures:
    - env: TASK=test:gas:ci
before_script:
  - rm -rf node_modules/websocket/.git && npm prune
script: "npm run $TASK"
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
